### ISSUE TITLE
error when building android keyboards "no such subcommand ndk"

### ISSUE THREAD

**Issue by ftyers** [divvun/kbdgen-archived#36]
```
fran@ipek:~/source/giellatekno/giella-core/kbdgen$ python3 -m kbdgen -t android examples/project-cux.yaml 
[I android:582] Getting source files from divvun/giella-ime master branch…
[I android:464] Adding 'cux' to './deps/giella-ime/app/src/main/res/values/donottranslate.xml'…
[I android:109] Updating XML strings…
[I android:538] Updating method definitions…
[I android:565] Embedding generated keyboard XML files…
[W android:276] No ZHFST files found.
[I android:331] Updating localisation values…
[W android:345] no icon supplied!
[I android:396] Building native components…
[I android:398] Building armv7-linux-androideabi architecture…
error: no such subcommand: `ndk`

	Did you mean `new`?

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 17, in <module>
    main()
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 11, in main
    sys.exit(run_cli())
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/cli.py", line 132, in run_cli
    x.generate(x.output_dir)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 145, in generate
    self.build(base, tree_id, self.is_release)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 418, in build
    os.path.join(jni_dir, "libdivvunspell.so"),
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './deps/giella-ime/../hfst-ospell-rs/target/armv7-linux-androideabi/release/libdivvunspell.so'
```

Versions:
```
$ apt-cache show  google-android-ndk-installer
Package: google-android-ndk-installer
Version: 13b

$ cargo --version
cargo 1.34.0

$ apt-cache show android-sdk
Package: android-sdk
Source: android-sdk-meta
Version: 25.0.0+10

$ svn info | grep Rev
Revision: 180268
Last Changed Rev: 180118
```

**Comment by bbqsrc** [comment]
`cargo install cargo-ndk`, then run again.

**Comment by ftyers** [comment]
That solves that error, thanks!
