### ISSUE TITLE
can't find crate for `core`

### ISSUE THREAD

**Issue by ftyers** [divvun/kbdgen-archived#39]
```
$ python3 -m kbdgen -t android examples/project-cux.yaml 
[I android:582] Getting source files from divvun/giella-ime master branch…
[I android:464] Adding 'cux' to './deps/giella-ime/app/src/main/res/values/donottranslate.xml'…
[I android:109] Updating XML strings…
[I android:538] Updating method definitions…
[I android:565] Embedding generated keyboard XML files…
[W android:276] No ZHFST files found.
[I android:331] Updating localisation values…
[W android:345] no icon supplied!
[I android:396] Building native components…
[I android:398] Building armv7-linux-androideabi architecture…
   Compiling semver-parser v0.7.0
   Compiling autocfg v0.1.1
   Compiling version_check v0.1.5
   Compiling libc v0.2.47
   Compiling proc-macro2 v0.4.20
   Compiling rand_core v0.3.0
   Compiling cfg-if v0.1.6
   Compiling unicode-xid v0.1.0
error[E0463]: can't find crate for `core`
  |
  = note: the `armv7-linux-androideabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `cfg-if`.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `armv7-linux-androideabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rand_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 17, in <module>
    main()
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 11, in main
    sys.exit(run_cli())
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/cli.py", line 132, in run_cli
    x.generate(x.output_dir)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 145, in generate
    self.build(base, tree_id, self.is_release)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 418, in build
    os.path.join(jni_dir, "libdivvunspell.so"),
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './deps/giella-ime/../hfst-ospell-rs/target/armv7-linux-androideabi/release/libdivvunspell.so'
```

**Comment by bbqsrc** [comment]
Oh, the targets for Rust are missing.

``` 
rustup target add aarch64-linux-android
rustup target add armv7-linux-androideabi
rustup target add i686-linux-android
```

I'll update the documentation, thanks!

**Comment by bbqsrc** [comment]
Okay, Android and iOS docs have been updated!

**Comment by ftyers** [comment]
Is there a way to do it without rustup?

When I try and install it, I get:

```
$ curl --proto '=https' --tlsv1.2 -Sf https://sh.rustup.rs | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 10652  100 10652    0     0  21738      0 --:--:-- --:--:-- --:--:-- 21738
info: downloading installer
error: it looks like you have an existing installation of Rust at:
error: /usr/bin
error: rustup cannot be installed alongside Rust. Please uninstall first
error: if this is what you want, restart the installation with `-y'
error: cannot install while Rust is installed
```

I'm running Debian with 
```
$ apt-cache show rustc
Package: rustc
Version: 1.34.2+dfsg1-1
```

**Comment by bbqsrc** [comment]
I do not know, sorry! `rustup` is officially managed by the Rust project and is the only way we support using Rust at this stage.

Maybe Debian packages other architecture targets somehow? You'll need to enquire with them.

**Comment by ftyers** [comment]
According to [this](http://zork.net/~st/jottings/rust-windows-and-debian.html), 

```
[toolchain.optional]
rust-std = ["aarch64-linux-android", "armv7-linux-androideabi", "i686-linux-android"]
```

might be the trick. I'm running it now, but on a slow internet connection. Will report back.
