### ISSUE TITLE
warning: unused import: `Cursor`

### ISSUE THREAD

**Issue by ftyers** [divvun/kbdgen-archived#40]
```
$ python3 -m kbdgen -t android examples/project-cux.yaml 
[I android:582] Getting source files from divvun/giella-ime master branch…
[I android:464] Adding 'cux' to './deps/giella-ime/app/src/main/res/values/donottranslate.xml'…
[I android:109] Updating XML strings…
[I android:538] Updating method definitions…
[I android:565] Embedding generated keyboard XML files…
[W android:276] No ZHFST files found.
[I android:331] Updating localisation values…
[W android:345] no icon supplied!
[I android:396] Building native components…
[I android:398] Building armv7-linux-androideabi architecture…
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.47
   Compiling version_check v0.1.5
   Compiling autocfg v0.1.1
   Compiling proc-macro2 v0.4.20
   Compiling rand_core v0.3.0
   Compiling unicode-xid v0.1.0
   Compiling void v1.0.2
   Compiling cfg-if v0.1.6
   Compiling crc32fast v1.1.2
   Compiling unic-char-range v0.9.0
   Compiling stable_deref_trait v1.1.1
   Compiling unic-common v0.9.0
   Compiling ucd-util v0.1.2
   Compiling serde v1.0.89
   Compiling lazy_static v1.3.0
   Compiling regex v1.0.5
   Compiling byteorder v1.3.1
   Compiling ryu v0.2.7
   Compiling quick-error v1.2.2
   Compiling scopeguard v0.3.3
   Compiling utf8-ranges v1.0.2
   Compiling itoa v0.4.3
   Compiling remove_dir_all v0.5.1
   Compiling error-chain v0.12.0
   Compiling termcolor v1.0.4
   Compiling podio v0.1.5
   Compiling xml-rs v0.8.0
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.4
   Compiling semver v0.9.0
   Compiling unreachable v1.0.0
   Compiling log v0.4.6
   Compiling memchr v2.1.1
   Compiling owning_ref v0.3.3
   Compiling unic-char-property v0.9.0
   Compiling unic-ucd-version v0.9.0
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.6.2
   Compiling humantime v1.1.1
   Compiling smallvec v0.6.5
   Compiling rustc_version v0.2.3
   Compiling unic-ucd-segment v0.9.0
   Compiling unic-ucd-common v0.9.0
   Compiling lock_api v0.1.4
   Compiling rand_os v0.1.1
   Compiling atty v0.2.11
   Compiling rand v0.4.6
   Compiling memmap v0.7.0
   Compiling rand_pcg v0.1.1
   Compiling parking_lot_core v0.4.0
   Compiling unic-segment v0.9.0
   Compiling quote v0.6.9
   Compiling zip v0.5.0
   Compiling hashbrown v0.1.5
   Compiling fxhash v0.2.1
   Compiling aho-corasick v0.6.9
   Compiling tempdir v0.3.7
   Compiling syn v0.15.25
   Compiling serde_json v1.0.39
   Compiling serde-xml-rs v0.3.0 (https://github.com/bbqsrc/serde-xml-rs#dfae8c0b)
   Compiling parking_lot v0.7.1
   Compiling serde_derive v1.0.89
   Compiling env_logger v0.6.1
   Compiling divvunspell v0.3.0 (/home/fran/source/giellatekno/giella-core/kbdgen/deps/hfst-ospell-rs)
warning: unused import: `Cursor`
 --> src/archive/mod.rs:7:15
  |
7 | use std::io::{Cursor, Seek};
  |               ^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `Transducer`
  --> src/archive/mod.rs:11:25
   |
11 | use crate::transducer::{Transducer, HfstTransducer};
   |                         ^^^^^^^^^^

warning: unused import: `uint32_t`
 --> src/ffi/mod.rs:1:37
  |
1 | use libc::{c_char, size_t, uint8_t, uint32_t};
  |                                     ^^^^^^^^

warning: unused import: `null_mut`
 --> src/ffi/mod.rs:3:22
  |
3 | use std::ptr::{null, null_mut};
  |                      ^^^^^^^^

warning: unused import: `SpellerArchiveError`
 --> src/ffi/mod.rs:7:38
  |
7 | use crate::archive::{SpellerArchive, SpellerArchiveError};
  |                                      ^^^^^^^^^^^^^^^^^^^

warning: unused import: `FlagDiacriticOperator`
 --> src/speller/worker.rs:9:61
  |
9 | use crate::types::{SymbolNumber, Weight, SpellerWorkerMode, FlagDiacriticOperator};
  |                                                             ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `std::io::Write`
   --> src/speller/worker.rs:578:13
    |
578 |         use std::io::Write;
    |             ^^^^^^^^^^^^^^

warning: unused import: `HashSet`
 --> src/speller/mod.rs:4:26
  |
4 | use hashbrown::{HashMap, HashSet};
  |                          ^^^^^^^

warning: unused import: `crate::transducer::tree_node::TreeNode`
 --> src/speller/mod.rs:9:5
  |
9 | use crate::transducer::tree_node::TreeNode;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `FlagDiacriticOperator`
  --> src/speller/mod.rs:11:61
   |
11 | use crate::types::{SymbolNumber, Weight, SpellerWorkerMode, FlagDiacriticOperator};
   |                                                             ^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `unic_ucd_common::is_alphanumeric`
 --> src/tokenizer/mod.rs:5:5
  |
5 | use unic_ucd_common::is_alphanumeric;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `hashbrown::HashSet`
 --> src/tokenizer/caps.rs:1:5
  |
1 | use hashbrown::HashSet;
  |     ^^^^^^^^^^^^^^^^^^

warning: unused import: `std::iter::FromIterator`
 --> src/tokenizer/caps.rs:2:5
  |
2 | use std::iter::FromIterator;
  |     ^^^^^^^^^^^^^^^^^^^^^^^

warning: unused import: `super::*`
  --> src/tokenizer/caps.rs:78:9
   |
78 |     use super::*;
   |         ^^^^^^^^

warning: unused import: `Transducer`
  --> src/ffi/mod.rs:11:25
   |
11 | use crate::transducer::{Transducer, chunk::{ChfstTransducer, ChfstBundle}};
   |                         ^^^^^^^^^^

warning: unused import: `Write`
 --> src/transducer/transition_table.rs:4:23
  |
4 | use std::io::{Cursor, Write};
  |                       ^^^^^

warning: unused variable: `handle`
  --> src/ffi/mod.rs:69:37
   |
69 | pub extern fn chfst_meta_get_locale(handle: *mut Speller<ChfstTransducer>) -> *mut c_char {
   |                                     ^^^^^^ help: consider prefixing with an underscore: `_handle`
   |
   = note: #[warn(unused_variables)] on by default

warning: value assigned to `max_weight` is never read
   --> src/speller/worker.rs:572:17
    |
572 |         let mut max_weight = speller_max_weight(&self.config);
    |                 ^^^^^^^^^^
    |
    = note: #[warn(unused_assignments)] on by default
    = help: maybe it is overwritten before being read?

warning: variable does not need to be mutable
   --> src/speller/worker.rs:550:13
    |
550 |         let mut max_weight = speller_max_weight(&self.config);
    |             ----^^^^^^^^^^
    |             |
    |             help: remove this `mut`
    |
    = note: #[warn(unused_mut)] on by default

error: linker `/home/fran/source/android-ndk-r19c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc` not found
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `divvunspell`.

To learn more, run the command again with --verbose.
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 17, in <module>
    main()
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/__main__.py", line 11, in main
    sys.exit(run_cli())
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/cli.py", line 132, in run_cli
    x.generate(x.output_dir)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 145, in generate
    self.build(base, tree_id, self.is_release)
  File "/home/fran/source/giellatekno/giella-core/kbdgen/kbdgen/gen/android.py", line 418, in build
    os.path.join(jni_dir, "libdivvunspell.so"),
  File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './deps/giella-ime/../hfst-ospell-rs/target/armv7-linux-androideabi/release/libdivvunspell.so'
```

**Comment by bbqsrc** [comment]
Run `cargo install cargo-ndk --force` to update it to 0.3.0, then try running it again.

**Comment by ftyers** [comment]
That seemed to work, still getting errors with `divvunspell`, but it has got to the `[I android:425] Generating .apk…` part. I'll close this issue and open another one for the divvunspell problems.
